/**
 * Shared IPC channel catalog.
 * Main, preload, and renderer modules import these names so cross-process event
 * strings have one source of truth. Add every new IPC workflow here first.
 */
const CHANNELS = {
  // Connection configuration.
  SET_PORTAL: "PORTAL-NAME",
  SET_KEY: "INTEGRATION-KEY",
  SET_PASS: "INTEGRATION-PASS",

  // Single-record lookup and actions.
  SET_RECORD: "RECORD",
  CHANGE_RECORD: "CHANGE-RECORD-BUTTON",
  DELETE_RECORD: "DELETE-RECORD-BUTTON",

  // CSV loading and activity feed.
  OPEN_FILE_DIALOG: "OPEN-FILE-DIALOG",
  FEED_BOX_CLEAR: "FEED-BOX-CLEAR",
  FEED_BOX: "FEED-BOX",
  FEED_RECORDS_REPLACE: "FEED-RECORDS-REPLACE",
  FEED_SOURCE: "FEED-SOURCE",
  SELECTED_FILE_COUNT: "RECORD-COUNT",

  // Record editor and confirmation dialogs.
  RECORD_INFO: "RECORD-INFO",
  CONFIRM_UPDATE: "CONFIRM-UPDATE",
  UPDATE_CONFIRM: "UPDATE-CONFIRM",
  DELETE_CONFIRM: "DELETE-CONFIRM",
  UPDATE_CANCEL: "UPDATE-CANCEL",
  CONFIRMATION_CANCEL: "CONFIRMATION-CANCEL",
  DELETE_ALL: "DELETE-ALL",
  DELETE_ALL_CONFIRM: "DELETE-ALL-CONFIRM",
  DELETE_DISPLAYED: "DELETE-DISPLAYED",
  DELETE_DISPLAYED_CONFIRM: "DELETE-DISPLAYED-CONFIRM",
  GET_DELETE_SCOPE: "GET-DELETE-SCOPE",

  // Runtime mode and account-level deletion.
  TOGGLE_MODE: "TOGGLE-MODE",
  DELETE_ACCOUNT: "DELETE-ACCOUNT",
  DELETE_ACCOUNT_CONFIRM: "DELETE-ACCOUNT-CONFIRM",

  // Shared UI notifications, portal-list loading, and bulk-deletion lifecycle.
  SEND_RECORD_TYPE: "SEND-RECORD-TYPE",
  TOGGLE_DELETE: "TOGGLE-DELETE",
  DELETED_FILE_COUNT: "DELETE-COUNT",
  CLEAR_DELETE_OPTIONS: "CLEAR_DELETE_OPTIONS",
  ACTION_RESPONSE: "ACTION-RESPONSE",
  BULK_DELETE_RECORD: "bulk-delete-record",
  ACTIVATE_TEXT_LIST: "ACTIVATE-TEXT-LIST",
  FETCH_PORTAL_CUSTOMERS: "FETCH-PORTAL-CUSTOMERS",
  CANCEL_DELETION: "CANCEL-DELETION",
  DELETION_PROGRESS: "DELETION-PROGRESS",
  RESUME_DELETION: "RESUME-DELETION",
  RETRY_FAILED_DELETIONS: "RETRY-FAILED-DELETIONS",
};

module.exports = CHANNELS;
