/**
 * Shared IPC channel catalog.
 * Main, preload, and renderer modules import these names so cross-process event
 * strings have one source of truth. Add every new IPC workflow here first.
 */
const CHANNELS = {
  // Connection configuration.
  SET_PORTAL: "PORTAL-NAME",
  SET_KEY: "INTEGRATION-KEY",
  SET_PASS: "INTEGRATION-PASS",
  SET_CONFIGURATION: "SET-CONFIGURATION",

  // Session-only renderer workspace snapshots used when switching app pages.
  GET_WORKSPACE_STATE: "GET-WORKSPACE-STATE",
  SET_WORKSPACE_STATE: "SET-WORKSPACE-STATE",
  OPEN_HELP: "OPEN-HELP",

  // Single-record lookup and actions.
  SET_RECORD: "RECORD",
  CHANGE_RECORD: "CHANGE-RECORD-BUTTON",
  DELETE_RECORD: "DELETE-RECORD-BUTTON",

  // CSV loading and activity feed.
  OPEN_FILE_DIALOG: "OPEN-FILE-DIALOG",
  FEED_BOX_CLEAR: "FEED-BOX-CLEAR",
  FEED_BOX: "FEED-BOX",
  FEED_RECORDS_REPLACE: "FEED-RECORDS-REPLACE",
  FEED_SOURCE: "FEED-SOURCE",
  SELECTED_FILE_COUNT: "RECORD-COUNT",

  // Record editor and confirmation dialogs.
  RECORD_INFO: "RECORD-INFO",
  CONFIRM_UPDATE: "CONFIRM-UPDATE",
  UPDATE_CONFIRM: "UPDATE-CONFIRM",
  DELETE_CONFIRM: "DELETE-CONFIRM",
  UPDATE_CANCEL: "UPDATE-CANCEL",
  CONFIRMATION_CANCEL: "CONFIRMATION-CANCEL",
  DELETE_ALL: "DELETE-ALL",
  DELETE_ALL_CONFIRM: "DELETE-ALL-CONFIRM",
  DELETE_DISPLAYED: "DELETE-DISPLAYED",
  DELETE_DISPLAYED_CONFIRM: "DELETE-DISPLAYED-CONFIRM",
  GET_DELETE_SCOPE: "GET-DELETE-SCOPE",

  // Runtime mode and account-level deletion.
  TOGGLE_MODE: "TOGGLE-MODE",
  DELETE_ACCOUNT: "DELETE-ACCOUNT",
  DELETE_ACCOUNT_CONFIRM: "DELETE-ACCOUNT-CONFIRM",

  // Shared UI notifications, portal-list loading, and bulk-deletion lifecycle.
  SEND_RECORD_TYPE: "SEND-RECORD-TYPE",
  TOGGLE_DELETE: "TOGGLE-DELETE",
  DELETED_FILE_COUNT: "DELETE-COUNT",
  CLEAR_DELETE_OPTIONS: "CLEAR_DELETE_OPTIONS",
  ACTION_RESPONSE: "ACTION-RESPONSE",
  BULK_DELETE_RECORD: "bulk-delete-record",
  ACTIVATE_TEXT_LIST: "ACTIVATE-TEXT-LIST",
  FETCH_PORTAL_CUSTOMERS: "FETCH-PORTAL-CUSTOMERS",
  CANCEL_DELETION: "CANCEL-DELETION",
  DELETION_PROGRESS: "DELETION-PROGRESS",
  GET_DELETION_PROGRESS: "GET-DELETION-PROGRESS",
  RESUME_DELETION: "RESUME-DELETION",
  RETRY_FAILED_DELETIONS: "RETRY-FAILED-DELETIONS",

  // AutoPay customer discovery, templates, contracts, imports, and bulk work.
  GET_CONNECTION_STATUS: "GET-CONNECTION-STATUS",
  AUTOPAY_LIST_CUSTOMERS: "AUTOPAY-LIST-CUSTOMERS",
  AUTOPAY_LIST_TEMPLATES: "AUTOPAY-LIST-TEMPLATES",
  AUTOPAY_SAVE_TEMPLATE: "AUTOPAY-SAVE-TEMPLATE",
  AUTOPAY_GET_CONTRACT: "AUTOPAY-GET-CONTRACT",
  AUTOPAY_SAVE_CONTRACT: "AUTOPAY-SAVE-CONTRACT",
  AUTOPAY_DELETE_CONTRACT: "AUTOPAY-DELETE-CONTRACT",
  AUTOPAY_IMPORT_WORKBOOK: "AUTOPAY-IMPORT-WORKBOOK",
  AUTOPAY_DOWNLOAD_WORKBOOK: "AUTOPAY-DOWNLOAD-WORKBOOK",
  AUTOPAY_EXPORT_CUSTOMERS: "AUTOPAY-EXPORT-CUSTOMERS",
  AUTOPAY_EXPORT_PROGRESS: "AUTOPAY-EXPORT-PROGRESS",
  AUTOPAY_START_BULK: "AUTOPAY-START-BULK",
  AUTOPAY_GET_PROGRESS: "AUTOPAY-GET-PROGRESS",
  AUTOPAY_CLEAR_RESULTS: "AUTOPAY-CLEAR-RESULTS",
  AUTOPAY_CANCEL_BULK: "AUTOPAY-CANCEL-BULK",
  AUTOPAY_RESUME_BULK: "AUTOPAY-RESUME-BULK",
  AUTOPAY_RETRY_BULK: "AUTOPAY-RETRY-BULK",
  AUTOPAY_PROGRESS: "AUTOPAY-PROGRESS",
  AUTOPAY_RESULT: "AUTOPAY-RESULT",
};

module.exports = CHANNELS;
