const CHANNELS = { // Different channels defined in CHANNELS list used for ipc communication
    SET_PORTAL: "PORTAL-NAME",
    SET_KEY: "INTEGRATION-KEY",
    SET_PASS: "INTEGRATION-PASS",
    SET_RECORD: "RECORD",
    CHANGE_RECORD: "CHANGE-RECORD-BUTTON",
    DELETE_RECORD: "DELETE-RECORD-BUTTON",
    OPEN_FILE_DIALOG: "OPEN-FILE-DIALOG",
    FEED_BOX_CLEAR: "FEED-BOX-CLEAR",
    FEED_BOX: "FEED-BOX",
    SELECTED_FILE_COUNT: "RECORD-COUNT",
    RECORD_INFO: "RECORD-INFO",
    CONFIRM_UPDATE: "CONFIRM-UPDATE",
    UPDATE_CONFIRM: "UPDATE-CONFIRM",
    DELETE_CONFIRM: "DELETE-CONFIRM",
    UPDATE_CANCEL: "UPDATE-CANCEL",
    CONFIRMATION_CANCEL: "CONFIRMATION-CANCEL",
    DELETE_ALL: "DELETE-ALL",
    DELETE_ALL_CONFIRM: "DELETE-ALL-CONFIRM",
    DELETE_DISPLAYED: "DELETE-DISPLAYED",
    DELETE_DISPLAYED_CONFIRM: "DELETE-DISPLAYED-CONFIRM",
    TOGGLE_MODE: "TOGGLE-MODE",
    DELETE_ACCOUNT: "DELETE-ACCOUNT",
    DELETE_ACCOUNT_CONFIRM: "DELETE-ACCOUNT-CONFIRM",
    SEND_RECORD_TYPE: "SEND-RECORD-TYPE",
    TOGGLE_DELETE: "TOGGLE-DELETE",
    DELETED_FILE_COUNT: "DELETE-COUNT",
    CLEAR_DELETE_OPTIONS: "CLEAR_DELETE_OPTIONS"
  };
  
  module.exports = CHANNELS;
  